name: deploy_lambda_scribe_proxy

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/deploy_lambda_scribe_proxy.yml'
      - 'fbossci-aws-lambas/us-east-1/scribe-proxy/**'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: appleboy/lambda-action@1e05c1377056f21ebb2ce69b910bc16b943c2a66
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: gh-ci-scribe-proxy
          source: fbossci-aws-lambas/us-east-1/scribe-proxy/lambda_function.py
