name: Push CI Docker Base

on:
  push:
    branches:
      - master
    paths:
      - 'ci-docker-base/**'
      - '.github/workflows/push_ci_docker_base.yml'

jobs:
  cilint-clang-tidy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push
        run: |
          set -ex
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          cd ci-docker-base
          docker build . --tag ghcr.io/pytorch/cilint-clang-tidy:$GITHUB_SHA -f Dockerfile.cilint-clang-tidy
          docker push ghcr.io/pytorch/cilint-clang-tidy:$GITHUB_SHA

